#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = encode_config
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/ITarget.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/ITarget.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Repository.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Repository.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/_gen.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/_gen.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Library.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Library.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/PackageContents.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/PackageContents.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/UCArm9.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/UCArm9.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/BuildEnvironment.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/io/package.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/io/package.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Linux86.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Linux86.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/om2.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/om2.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Executable.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Executable.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Clock.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Clock.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Trace.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Trace.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Mingw.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Mingw.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Utils.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Utils.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/package.xs.xdt
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/template.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/template.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/package.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/package.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen2.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen2.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/package.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/package.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/tools/configuro/template/compiler.opt.xdt
package.mak: config.bld
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/package.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/package.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/IPackage.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/IPackage.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Script.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Script.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/io/File.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/io/File.xs
package.mak: package.bld
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xdc.tci:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xdc.tci
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/include/utils.tci:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/include/utils.tci
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITarget.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITarget.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITargetFilter.xs
/home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/MVArm9.xs:
package.mak: /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/MVArm9.xs
endif

gnu.targets.MVArm9.rootDir ?= /opt/mv_pro_5.0/montavista/pro/devkit/arm/v5t_le
gnu.targets.packageBase ?= /home/plc/workdir/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o470MV
.PHONY: all,470MV .dlls,470MV .executables,470MV test,470MV
all,470MV: .executables,470MV
.executables,470MV: .libraries,470MV
.executables,470MV: .dlls,470MV
.dlls,470MV: .libraries,470MV
.libraries,470MV: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,470MV
	@$(ECHO) xdc .executables,470MV
	@$(ECHO) xdc .libraries,470MV
	@$(ECHO) xdc .dlls,470MV


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_encode_config.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package encode_config" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,470MV .executables: encode.x470MV

-include package/cfg/encode_x470MV.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/encode_x470MV.dep
endif
package/cfg/encode_x470MV.o470MV : | package/cfg/encode_x470MV.xdl
encode.x470MV:
	$(RM) $@
	@$(MSG) lnk470MV $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-gcc    -o $@ package/cfg/encode_x470MV.o470MV  package/cfg/encode_x470MV.xdl  -lstdc++ -L$(gnu.targets.MVArm9.rootDir)/armv5tl-montavista-linux-gnueabi/lib
	
encode.x470MV:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,470MV))
encode.x470MV package/cfg/encode_x470MV.c: .libraries,470MV
endif

package/cfg/encode_x470MV.c package/cfg/encode_x470MV.h package/cfg/encode_x470MV.xdl: override _PROG_NAME := encode.x470MV
package/cfg/encode_x470MV.c: package/cfg/encode_x470MV.cfg
encode.test test,470MV test: encode.x470MV.test

encode.x470MV.test:: encode.x470MV
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 encode.x470MV.test
else
	@$(MSG) running $<  ...
	$(call EXEC.encode.x470MV, ) 
endif


clean:: clean,470MV
	-$(RM) package/cfg/encode_x470MV.cfg
	-$(RM) package/cfg/encode_x470MV.dep
	-$(RM) package/cfg/encode_x470MV.c
	-$(RM) package/cfg/encode_x470MV.xdc.inc

clean,470MV::
	-$(RM) encode.x470MV
	-$(RM) .tmp,encode.x470MV,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
encode_x470MV.s470MV,copy : package/cfg/encode_x470MV.s470MV
encode_x470MV.o470MV,copy : package/cfg/encode_x470MV.o470MV

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,encode_config
encode_config.tar: package/build.cfg
encode_config.tar: package/package.ext.xml
encode_config.tar: package/package.xdc.inc
encode_config.tar: package/package.bld.xml
encode_config.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/encode_config.tar.dep
endif
package/rel/encode_config/encode_config/package/package.rel.xml:

encode_config.tar: package/rel/encode_config.xdc.inc package/rel/encode_config/encode_config/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/encode_config.xdc.inc,package/rel/encode_config.tar.dep)


release release,encode_config: all encode_config.tar
clean:: .clean
	-$(RM) encode_config.tar
	-$(RM) package/rel/encode_config.xdc.inc
	-$(RM) package/rel/encode_config.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
